### ISSUE TITLE
The results of sink/transformer/windowed under outputs_*/ folders are all the same

### ISSUE THREAD

**Issue by ZiweiHe** [tomaarsen/attention_sinks#18]
Hi,

The results you gave [here](https://github.com/tomaarsen/attention_sinks/tree/main/benchmark) are problematic. Under the same directory, the results of 3 different attention types are identical.

**Comment by tomaarsen** [comment]
Hello!

They indeed start equivalent for the first 1024 tokens, but they differ after that. This is because the `windowed` and `attention_sinks` approaches in the benchmarks use a window size of 1024, before which the three approaches are identical. See for example token 4000 for evidence that the results are not identical:
* [`attention_sinks` at 4k](https://github.com/tomaarsen/attention_sinks/blob/main/benchmark/outputs_falcon_7b/attention_sinks.csv#L4000)
* [`windowed` at 4k](https://github.com/tomaarsen/attention_sinks/blob/main/benchmark/outputs_falcon_7b/windowed.csv#L4000)
* [`transformers` at 4k](https://github.com/tomaarsen/attention_sinks/blob/main/benchmark/outputs_falcon_7b/transformers.csv#L4000)

Also, these figures in the README are direct plots of these .csv files:
![image](https://github.com/tomaarsen/attention_sinks/assets/37621491/ca15d5a6-f91c-4741-8326-49bca039edce)
As you can see, they're not identical.

I hope that clears it up!

- Tom Aarsen

**Comment by ZiweiHe** [comment]
Oh my mistake, thank you for your reply. Plese feel free to delete this issue!

**Comment by tomaarsen** [comment]
No worries!
